server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
        
spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: wltjdals422
    password: dbgmltn0422#
    smtp.auth: true
    smtp.starttls.enable: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dodream?serverTimezone=Asia/Seoul
    username: root
    password: root
    
    
  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    #show-sql: true
    #properties:
    #  hibernate.format_sql: true
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 995380518815-6u3ulp46ahsdckqnra5kee07mufcfuiq.apps.googleusercontent.com
            client-secret: -EIOhv8qi6YYgX2PnzidY8I-
            scope:
            - email
            - profile
            
          facebook:
            client-id: 447966159676824
            client-secret: c8fe2c944384b01df522fcea40c3b603
            scope:
            - email
            - public_profile
          
          naver:
            client-id: fr8s0Pzz2AAFa6VMgoyT
            client-secret: Fk__UWIsxX
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-id: ccd2c184a87ab5205b193da983dd46f4
            client-secret: 8hNvy0iNQqpNJTuzNZ4QevAsZReZ91Hw
            scope:
            - profile
            - account_email
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 뜨는 창!
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰 받을 때 사용되는 곳
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 받을 때 사용되는 곳
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌. (getAttributes)
            
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 로그인 뜨는 창!
            token-uri: https://kauth.kakao.com/oauth/token # 토큰 받을 때 사용되는 곳
            user-info-uri: https://kapi.kakao.com/v2/user/me # 프로필 정보를 받을 때 사용되는 곳 
            user-name-attribute: id #회원정보를 json으로 받는데 id라는 키값으로 네이버가 리턴해줌. (getAttributes)
           
social:
  password: dodream1234
  
api:
  sms:
    api-key: NCSOSP7IP6LI47WT
    api-secret: EVJACJDVXCTXW2ODT28UXRDIZHPZ9TUL
    send-phone: '01068363758'
    
summernote:
  upload: Users/wltjd/Desktop/Dodream/dodream-boot/dodream/src/main/resources/static/image/summernote/
