server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
        
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    help: 
      host: smtp.gmail.com
      port: 587
      username: dodream.help@gmail.com # gmail ID
      password: enemfla1! # gmail PW
      nickname: help두드림터치 # mail 발송시 표기되는 송신자 이름 
    desk:
      host: smtp.gmail.com
      port: 587
      username: dodream.desk@gmail.com # gmail ID
      password: enemfla1! # gmail PW
      nickname: 회원가입두드림터치 # mail 발송시 표기되는 송신자 이름 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.dodreamtouch.co.kr/dodream777?serverTimezone=Asia/Seoul 
    username: dodream777 
    password: tomleegood77 
    
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dodream?serverTimezone=Asia/Seoul
#    username: root
#    password: rootroot
    
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://walab.handong.edu/dodream?serverTimezone=Asia/Seoul
#    username: dodream
#    password: wacs0422#
    
    
  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    #show-sql: true
    #properties:
    #  hibernate.format_sql: true
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 468483821039-ofginhbfm4edc44f643v8m9mupbj8eaq.apps.googleusercontent.com
            client-secret: eARAiupOcUj_6jvUtjNr9Z7p
            redirect-uri: https://dodreamtouch.co.kr/login/oauth2/code/google
            scope:
            - email
            - profile
            
#          facebook:
#            client-id: 447966159676824
#            client-secret: c8fe2c944384b01df522fcea40c3b603
#            scope:
#            - email
#            - public_profile
          
          naver:
            client-id: V2w3AgJchgKhycTL7zo5 #fr8s0Pzz2AAFa6VMgoyT
            client-secret: QwOBG8I4aX #Fk__UWIsxX
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            #redirect-uri: http://localhost:8080/login/oauth2/code/naver
            redirect-uri: https://dodreamtouch.co.kr/login/oauth2/code/naver

          kakao:
            client-id: 75934403dc0faf5d40216188a499879a #ccd2c184a87ab5205b193da983dd46f4
            client-secret: ovA9LfSsiW9pUXcKla2olfSe9UFXXPV4 #8hNvy0iNQqpNJTuzNZ4QevAsZReZ91Hw
            scope:
            - profile
            #- account_email
            client-name: kakao
            authorization-grant-type: authorization_code
            #redirect-uri: http://localhost:8080/login/oauth2/code/kakao # localhost
            redirect-uri: https://dodreamtouch.co.kr/login/oauth2/code/kakao # dodreamtouch.com
            client-authentication-method: POST
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 뜨는 창!
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰 받을 때 사용되는 곳
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 받을 때 사용되는 곳
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌. (getAttributes)
            
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 로그인 뜨는 창!
            token-uri: https://kauth.kakao.com/oauth/token # 토큰 받을 때 사용되는 곳
            user-info-uri: https://kapi.kakao.com/v2/user/me # 프로필 정보를 받을 때 사용되는 곳 
            user-name-attribute: id #회원정보를 json으로 받는데 id라는 키값으로 네이버가 리턴해줌. (getAttributes)
           
social:
  password: dodream1234
 
#sms api / email api 정보
api:
  sms:
    api-key: NCSNSWTIYYUJDSSN
    api-secret: 9FCAM0HOR6RYUJLVUWGUPEVQJE1YAICE
    send-phone: '0542621070'

summernote:
  upload: /dodream777/tomcat/webapps/ROOT/WEB-INF/classes/static/image/summernote/  
  #upload: /Users/yechankim/git/dodream/src/main/resources/static/image/summernote/
  
request:
  interval: 60